### ISSUE TITLE
Add section for EVM documentation to https://docs.edgewa.re/ and populate with introductory task output.

### ISSUE THREAD

**Issue by drewstone** [hicommonwealth/edgeware-documentation#11]
Add entry into gitbook and populate with results from running the simple tasks of deploying tasks on Edgeware/moonbeam like chains.

**Comment by ShankarWarang** [comment]
We already have https://docs.edgewa.re/edgeware-runtime/evm 
and https://docs.edgewa.re/quickstart/deploy-an-evm-contract
So should we close this issue @drewstone?
