### ISSUE TITLE
Edit the Readme to indicate that adding pages requires you to add the page refs to Summary.MD

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/edgeware-documentation#29]
[Summary.md](https://github.com/hicommonwealth/edgeware-documentation/blob/master/docs/SUMMARY.md) is what Gitbooks uses to build the pretty frontend

**Comment by Camnaz** [comment]
https://github.com/Edgeware-Network/edgeware-documentation/commit/f0e150ef8afb1bce0329888c4e46827295dbcc93
