### ISSUE TITLE
Linking an idenity to ENS is no Quick Start material and needs clarifying

### ISSUE THREAD

**Issue by drewstone** [hicommonwealth/edgeware-documentation#49]
Firstly, this is not a quick start concept.
Secondly, this is poorly communicated and formatted.
Thirdly, it links to a notion which links to a polkadot link.

https://docs.edgewa.re/quickstart/create-an-edgeware-identity#add-an-address-to-an-ens-domain

**Comment by Camnaz** [comment]
Resolved: https://github.com/Edgeware-Network/edgeware-documentation/commit/ca4af167a8d413dd4fc3d279fb603851d2cdbce3
