### ISSUE TITLE
Testnet clarification: testnet or berlin?

### ISSUE THREAD

**Issue by tboeckmann** [hicommonwealth/edgeware-documentation#7]
The docs for Edgeware list 2 different groups of testnet nodes. This is not very clear which ones are current (although I suspect `berlinX.edgewa.re` are current).

Please could you update/ clarify to reflect the most recent values?

1. On this page: https://docs.edgewa.re/understanding-edgeware/staking/validation/frequently-used-commands

> Public nodes
> Commonwealth Labs maintains several public nodes for testnet v0.8:
testnet1.edgewa.re
testnet2.edgewa.re
testnet3.edgewa.re
testnet4.edgewa.re
testnet5.edgewa.re
testnet6.edgewa.re
Syntax:
wss://testnet1.edgewa.re
or (if wss: fails)
ws://testnet1.edgewa.re:9944

2. On this page: https://docs.edgewa.re/understanding-edgeware/networks

> wss://berlin1.edgewa.re
wss://berlin2.edgewa.re
wss://berlin3.edgewa.re
wss://berlin4.edgewa.re
wss://berlin5.edgewa.re
wss://berlin6.edgewa.re
wss://berlin7.edgewa.re
wss://berlin8.edgewa.re
wss://berlin9.edgewa.re
wss://berlin10.edgewa.re

**Comment by thomivy** [comment]
Added a link to the Networks page to prompt users to check the latest network details and revised syntax. Thanks!

https://github.com/hicommonwealth/edgeware-documentation/commit/94dccc66c25d388ed6c76b2a93071a8d9c0d6432
