### ISSUE TITLE
document error

### ISSUE THREAD

**Issue by Longfld** [hicommonwealth/edgeware-documentation#8]
A missing in validator monioring setting up page 
https://docs.edgewa.re/understanding-edgeware/staking/validation/setting-up-monitoring
before run test nodeup "node index.js", should run "npm install"

**Comment by thomivy** [comment]
Added a note that NPM is a prereq and the command : ) Thanks!

 https://github.com/hicommonwealth/edgeware-documentation/commit/7cc3066a87c7447d4a91e026cabf944fc4ed6fb8
