### ISSUE TITLE
typo after "Use monit to keep mmonit up:"

### ISSUE THREAD

**Issue by Longfld** [hicommonwealth/edgeware-documentation#9]
some typo in text/scripts written into /ete/monit/monitrc, here is correct context"
{
    echo 'check process mmonit with pidfile '`pwd`'/monit/logs/mmonit.pid'
    echo '  start program = "'`pwd`'/monit/bin/mmonit"'
    echo '  stop program = "'`pwd`'/monit/bin/mmonit stop"'
    echo 'set httpd port 2812 and use address localhost'
    echo '  allow localhost'
} > /etc/monit/monitrc

**Comment by thomivy** [comment]
Repaired! Thank you :)
